### PR TITLE
judges-action#203: add contributors in Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**
Need for https://github.com/zerocracy/judges-action/issues/203

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.73`

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for your review! You've snagged +4 points this time. Here's the breakdown: +4 base points, -10 for having only 2 comments (we aim for at least 6!), and +10 to keep you in the game. Remember, more comments can boost your score up to 8 points! Your [running balance](https://zerocracy.github.io/judges-action/zerocracy-vitals.html) is now +126. Keep up the good work and let's aim for more detailed reviews next time! 💪

**Comment by 0crat** [comment]
@Yegorov Thank you for your contribution! Your effort is appreciated, but we noticed a few areas for improvement. You've earned +4 points: +4 as a base reward, -4 for having only 3 comments (our policy encourages more thorough reviews), and +4 to ensure a minimum reward. We value your work and encourage you to [keep contributing](https://www.yegor256.com/2018/03/06/speed-vs-quality.html), focusing on both quantity and quality. Remember, more detailed code reviews can lead to better outcomes. Your current balance stands at [+164](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next contribution!

**Pull request merged**
