### PR TITLE
fake method `total_commits` for `github_graph`

### PR DESCRIPTION
**Pull request by Suban05**
it needs for https://github.com/zerocracy/judges-action/pull/355

### CODE REVIEW

**Comment by Suban05** [comment]
@Yegorov please review

**Review by Yegorov — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.71`

**Comment by 0crat** [comment]
@Yegorov Great job on the review! 🌟 You've earned +4 points: +4 base, adjusted for comments and hits-of-code. Keep up the good work! Your current balance is [+178](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Aim for more detailed reviews next time to maximize your rewards.

**Comment by 0crat** [comment]
@Suban05 Thanks for your contribution! Here's how your +4 points break down: +4 base, -4 for only 1 comment (policy suggests at least 6), -8 for 10 hits-of-code (policy recommends 20+), and +12 to meet the minimum reward. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and encouraging more review comments can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance: [+131](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
