### PR TITLE
fix missing require (ref: #43)

### PR DESCRIPTION
**Pull request by Yegorov**
Also fixed this error: https://github.com/zerocracy/judges-action/actions/runs/10150746329/job/28068526656

### CODE REVIEW

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.34`

**Comment by 0crat** [comment]
@Yegorov It is [not a good idea](https://www.yegor256.com/2014/04/15/github-guidelines.html) to name Git branches the way you named this one: "`fix-build`". You've earned -10 points. Next time, better give your branch the same name as the number of the ticket that you are solving. In this case, a perfect name, for example, would be "`44`". Your running balance is [+45](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Comment by 0crat** [comment]
@Yegorov Thanks for the contribution! You've earned +5 points for this: +30 as a basis; -15 for the lack of code review; -10 for too few (0) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+35](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Comment by Yegorov** [comment]
> It is not a good idea to name Git branches the way you named this one: "fix-build". You've earned -10 points. Next time, better give your branch the same name as the number of the ticket that you are solving.

@yegor256 
Ок, but how then to name a branch if there is no issue, and the changes is small, which does not require a large description of the problem.
Or creation issue is mandatory for each PR?

**Pull request merged**
