### PR TITLE
judges-action#194: add pull_requests to Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**
Need for https://github.com/zerocracy/judges-action/issues/194

### CODE REVIEW

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.67`

**Comment by 0crat** [comment]
@Suban05 Great job on the review! Here's how your +4 points break down: +4 base points, -24 for self-review, +16 for hits-of-code (capped), -10 for fewer than 6 comments, and +0.5 for 2 comments. We rounded up to 4 as per policy. Your [running balance](https://zerocracy.github.io/judges-action/zerocracy-vitals.html) is now +250. Keep up the good work! 👍

**Comment by 0crat** [comment]
@Yegorov Hey there, awesome job on your contribution! 🎉 You've snagged +4 points for this one. Here's the breakdown: +4 base points, -4 because we only got 2 comments (we love feedback!), and +4 to keep you motivated. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the great work coming. Your current balance is [+176](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's aim higher on the next one!

**Pull request merged**
