### PR TITLE
judges-action#202: add tree in Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**
Need for https://github.com/zerocracy/judges-action/issues/202

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.72`

**Comment by 0crat** [comment]
@Suban05 Hey there, code review superstar! 👍 You've just bagged +4 points for this review. Here's the breakdown: +4 base points, -24 for self-review (oops!), +1.25 for those 5 comments (keep 'em coming!), and +22.75 to hit our minimum reward. Remember, more comments and hits-of-code could boost your score next time! Your running balance is now [+134](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the great work!

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Nice work on your contribution! You've earned +4 points this time. Here's the breakdown: +4 base points, -4 because there were only 2 comments (we like to see more interaction!), and +4 to keep you motivated. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+178](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's aim higher next time! 💪

**Pull request merged**
