### PR TITLE
judges-action#238: add search_commits in Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**
Need for https://github.com/zerocracy/judges-action/issues/238

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.74`

**Comment by 0crat** [comment]
@Suban05 Great job on the review! 🌟 You've earned +4 points: +4 base, -10 for minimal comments, but +10 to ensure recognition. Your dedication is appreciated! Current balance: [+130](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the excellent work!

**Comment by 0crat** [comment]
@Yegorov Thank you for your contribution! Your effort is appreciated, but we need to address a few points. You've earned +4 points: +4 as a base reward, but -4 for having only 2 comments during review, which is below our policy's threshold of 6 comments. We encourage more detailed code reviews to improve overall quality. Please continue to [contribute](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) and engage in thorough code reviews. Your current balance stands at [+168](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
