### PR TITLE
judges-action#193: add compare to Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**
Need for https://github.com/zerocracy/judges-action/issues/193

### CODE REVIEW

**Comment by Yegorov** [comment]
@Suban05 please review

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@Suban05 Thank you for your code review contribution! We appreciate your effort, but there's room for improvement. As per our policy, you've earned 4 base points, but we had to deduct 10 points due to the low number of comments (only 2). To ensure you receive some recognition, we've adjusted your reward to 4 points, which is our minimum. Remember, more detailed feedback helps everyone improve. Your current balance stands at [+272](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for more comprehensive reviews next time! 💪

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.66`

**Comment by 0crat** [comment]
@Yegorov Thank you for your contribution! You've earned +4 points for this submission. Here's the breakdown: +4 as a base reward, -4 for having only 4 comments (which is below our target of 6), and +4 to ensure a minimum reward. While we appreciate your effort, please aim for more comprehensive code reviews in the future to maximize your points. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your updated balance is [+196](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
