### PR TITLE
judjes-action#156: add pull requests to Fbe::FakeOctokit#search_issues

### PR DESCRIPTION
**Pull request by Yegorov**

### CODE REVIEW

**Comment by yegor256** [comment]
@Yegorov in general, it's not good practice to make changes to the code without adding (or modifying) unit tests

**Comment by Yegorov** [comment]
@yegor256 ok, I added a test

**Comment by yegor256** [comment]
@Yegorov thanks!

**Comment by yegor256** [comment]
@Yegorov we need to release a new version?

**Comment by Yegorov** [comment]
> @Yegorov we need to release a new version?

@yegor256 yes of course

**Comment by Yegorov** [comment]
@yegor256 also see [this](https://github.com/zerocracy/judges-action/pull/205)

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.35`

**Comment by 0crat** [comment]
@Yegorov Thanks for the contribution! You've earned +11 points for this: +30 as a basis; +6 for the 69 hits-of-code that you wrote; -15 for the lack of code review; -10 for too few (2) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+40](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
