### PR TITLE
judges-action#191: add review_comments to Fbe::FakeOctokit

### PR DESCRIPTION
**Pull request by Yegorov**

### CODE REVIEW

**Review by Suban05 — APPROVED** [review]

**Comment by Yegorov** [comment]
@yegor256 please merge this pr

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.65`

**Comment by 0crat** [comment]
@Suban05 Great job on the review! 🌟 You've earned +4 points: base +4, -10 for limited comments, +10 bonus. Your dedication is appreciated! Current balance: [388 points](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the excellent work!

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Thanks for your code contribution! You've earned +4 points this time. Here's the breakdown: +4 as a base, -4 because there were only 2 comments (we love feedback!), and +4 to keep you motivated. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and active code reviews can boost your points next time. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+367](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Looking forward to your next awesome contribution! 💻🚀

**Pull request merged**
